version: '3.7'
services:
    postgres:
        image: postgres:14.3-alpine
        restart: always
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
    sparql-endpoint:
        image: atomgraph/fuseki
        command: --file /data/lib.rdf --update /library
        volumes:
            - ./data-files:/data:ro
    bibtex-to-rdf:
        build: bibtex-to-rdf
        volumes:
            - ./data-files:/app/rdfOut
    auth:
        build: auth-service
    gateway:
        build: gateway
        ports:
            - 5000:5000
