paths:
  - path: api/auth
    server: http://auth:5000/
    auth: False
  - path: api/bibtex
    server: http://bibtex-to-rdf:5000/
    auth: False
  - path: library
    server: http://sparql-endpoint:3030/
    auth: False
