import logging


properties = {
    'abstract': 'hasAbstract',
    'address': 'hasAddress',
    '': 'hasAffiliation',
    'annote': 'hasAnnotation',
    '': 'hasAuthor',
    'booktitle': 'hasBooktitle',
    'book': 'hasBooktitle',
    'chapter': 'hasChapter',
    '': 'hasContents',
    '': 'hasCopyright',
    'crossref': 'hasCrossref',
    'edition': 'hasEdition',
    'editors': 'hasEditor',
    'institution': 'hasInstitution',
    'isbn': 'hasISBN',
    'issn': 'hasISSN',
    'journal': 'hasJournal',
    'key': 'hasKey',
    'keywords': 'hasKeywords',
    'keyword': 'hasKeywords',
    '': 'hasLanguage',
    '': 'hasLCCN',
    'location': 'hasLocation',
    'month': 'hasMonth',
    '': 'hasMrnumber',
    'note': 'hasNote',
    'notes': 'hasNote',
    'number': 'hasNumber',
    'organization': 'hasOrganization',
    'pages': 'hasPages',
    'numpages': 'hasPages',
    '': 'hasPrice',
    'publisher': 'hasPublisher',
    'school': 'hasSchool',
    'series': 'hasSeries',
    '': 'hasSize',
    'title': 'hasTitle',
    'type': 'hasType',
    'url': 'hasURL',
    'volume': 'hasVolume',
    'year': 'hasYear',
    'howpublished': 'howPublished',
    '': 'pageChapterData',
    # Illegal not in definition
    'folder': 'hasFolder',
    'doiurl': 'hasDoiURL',
    'doi': 'hasDoiURL',
    'localurl': 'hasLocalURL',
    'localurl2': 'hasLocalURL2',
    'filing': 'hasFiling',
    'comment': 'hasComment',
    'comments': 'hasComment',
    'eprint': 'hasEprint',
    'issue_date': 'hasIssueDate',
    'acmid': 'hasACMID',
    'opttype': 'hasOptType',
    'optkey': 'hasOptKey',
    'optnumber': 'hasOptNumber',
    'optaddress': 'hasOptAddress',
    'optmonth': 'hasOptMonth',
    'optnote': 'hasOptNote',
    'optannote': 'hasOptAnnotation',
    'articleno': 'hasArticleNo',
    'url2': 'hasURL2',
    'oldurl': 'hasOldURL',
    'day': 'hasDay',
    'source': 'hasSource',
    'bibsource': 'hasSource',
    'urlpdf': 'hasURLPDF',
    'urlinfo': 'hasURLInfo',
    'urlspringer': 'hasURLSpringer',
}

def getProperty(name):
    name = name.lower()
    try:
        return properties[name]
    except KeyError:
        logging.error('Property not found: ' + name)
        return name