env:
  browser: true
  es2021: true
  vue/setup-compiler-macros: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
ignorePatterns:
  - "src/locales/*.json"
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  '@typescript-eslint/no-explicit-any':
    - off
  vue/html-indent:
    - error
    - tab
  vue/max-attributes-per-line:
    - warn
    - singleline: 5
      multiline: 1
